### PR TITLE
Logger with hierarchy

### PR DESCRIPTION
**Pull request by HuprichT**
With this changes you can now display Logs with Hierarchy. Works with popup() and fullscreen() if ypu provide suitable profile.
_( If you call popup() with a Profile it displays it in fullscreen anyways )_

~New Parameter is filled with DEFAULT VALUE 1.~

Should work with all Message types, I Tested:

- Exceptions
- Strings
- System Messages
- BAPIRET 
- Table of BAPIRET

To test it you simply have to fill new Parameter 'detlevel' and get the correct profile:

```
DATA(log) = zcl_logger_factory=>create_log(  ).

"First Group
log->s( obj_to_log = 'Airline 1' detlevel = '1' ).
log->e( obj_to_log = 'Passenger 123736GHB has not arrived at the Gate' detlevel = '2' ).

DATA: l_s_display_profile TYPE bal_s_prof.
CALL FUNCTION 'BAL_DSP_PROFILE_DETLEVEL_GET'
  IMPORTING
    e_s_display_profile = l_s_display_profile
  EXCEPTIONS
    OTHERS              = 1.
log->fullscreen( l_s_display_profile ).
```

Add new Logic. Resolves https://github.com/ABAP-Logger/ABAP-Logger/issues/140

### CODE REVIEW

**Comment by mbtools** [comment]
Resolved conflicts. Will get back to it after #135 is merged

**Review by mbtools — DISMISSED** [review]
Merge branch `main` into `logger_with_hierarchy` first, then merge here

**Comment by AlexandreHT** [comment]
> Merge branch `main` into `logger_with_hierarchy` first, then merge here

@HuprichT : do you have the option to rebase your branch (cf. https://github.blog/changelog/2022-02-03-more-ways-to-keep-your-pull-request-branch-up-to-date/)? I would be easier to resolve the conflicts and merge your PR.
Thanks!

**Comment by mbtools** [comment]
I did some testing...

1. Default for `detlevel`

I think it's a good enhancement. However, using `detlevel = '1'` as the default breaks existing implementations. This becomes apparent when executing the unit tests:

image

Change it to `detlevel TYPE ballevel OPTIONAL` and it works fine.

2. Structures and exceptions

`detlevel` should be passed to `add_structure` and `drill_down_into_exception` as well.

**Comment by HuprichT** [comment]
HI @mbtools , thanks for the suggestions. 

However I would like to discuss the Impacts based on that. The Unit Tests Fail because expected_data is not met. During the runtime we add detlevel = '1' to all Logs ( which does not change the output in reality though ) and this value is then missing. 

Now let's say detlevel is changed from `DEFAULT '1'` to `OPTIONAL`, now we have the problem: 
If a Log is build with hierarchy, and over the time the Developers forget to add detlevel to new entries, it's then not shown on the Output.

Example Code
```
DATA(log) = zcl_logger_factory=>create_log( object = 'ABAPUNIT' ).

log->s( obj_to_log = 'Airline 1' detlevel = '1' ).
log->s( obj_to_log = 'Passenger too late' detlevel = '2' ).

log->s( obj_to_log = 'Airline 2' detlevel = '1' ).
log->s( obj_to_log = 'Passenger too late' ). "Will not be display if provided with detlevel display profile

DATA: display_profile TYPE bal_s_prof .
CALL FUNCTION 'BAL_DSP_PROFILE_DETLEVEL_GET'
  IMPORTING
    e_s_display_profile = display_profile                 " Display Profile
  .

log->display_fullscreen( profile = display_profile ).
```

Output: Should vs. Actual:
image
image

So in the approach with `OPTIONAL` we would have to implement some kind of check inside if previous logs do have detlevel. If yes the default value '1' should be applied. 

What do you think?

**Comment by mbtools** [comment]
Currently, the expectation is that `detlevel` is 0 for all entries. We don't know what solutions exist that depend on it. So changing this would be breaking. 

If developers want a hierarchical log, they have to ensure themselves that detlevel is passed everywhere. That's no different than setting other optional parameters. Adding checks makes this more complex than necessary.

**Review by mbtools — APPROVED** [review]
Found a few issues during testing so I added unit tests and the missing `detlevel` parameters. Works fine now 👍 

PS: It's possible to pass something like `detlevel = 'A'` which makes no sense. It would also be nice to pass as an integer `detlevel = 1` as an alternative to char. But you can do these as follow-up if you like. 😉

**Comment by AlexandreHT** [comment]
Thanks to both of you!

**Pull request merged**
