### PR TITLE
Don't log system message when table or structure is empty

### PR DESCRIPTION
**Pull request by kjetil-kilhavn**
Check if object to log is initial after all the other checks. Simply moving the check seems to solve the problem. At least there are no regressions in the unit tests, and the two new tests pass as well.

Solved #168

### CODE REVIEW

**Comment by Kaszub09** [comment]
This fix relies on log_object being catched by `msg_type->type_kind` condition inside `add` method, which don't cover simpler variables like `c` or `i`. So something like
```
DATA empty_error_message TYPE c LENGTH 10.
anon_log->add( empty_error_message ).
```
logs system message instead of passed empty text. You could test it with
```
MESSAGE i003(bl) INTO where_used_list WITH 'This should' '*not*' 'be logged'.
...
data(messages) = anon_log->export_to_table( ).
cl_abap_unit_assert=>assert_false( xsdbool( line_exists( messages[ number = '003' ] ) ) ).
```
Altough that's arguably really rare case, so it may still be acceptable. :P

**Comment by kjetil-kilhavn** [comment]
I tried to change the implementation to detect if a string-like object to log is passed (character type, string, csequence), @Kaszub09 - but when nothing is passed, i.e. when you want to log the system message, typekind is typekind_char - so it seems to be impossible to distinguish between nothing passed and empty string passed without going back to IS SUPPLIED. 

The only way out of it is to make obj_to_log mandatory. It can be done as a non-breaking change by making sy the default, so that's what I have done, and hence the check for initial value in `add( )` could be removed. 

I added a test case for empty string, and now all three tests for initial values pass.

**Review by Kaszub09 — CHANGES_REQUESTED** [review]
Great idea with sy as default. Maybe also delete `syst_buffer` variable since it's no longer needed?

**Review by Kaszub09 — APPROVED** [review]
Looks good.

**Comment by Kaszub09** [comment]
But I guess @mbtools or @AlexandreHT must approve anyway. :P

**Comment by AlexandreHT** [comment]
Thanks for the PR. After reviewing, I think the following use case (which was advertised from [day one](https://community.sap.com/t5/application-development-blog-posts/show-scn-the-better-logger-i-promised/ba-p/13111590)) would not work anymore.
```ABAP 
MESSAGE e001(oo) WITH foo bar baz INTO dummy.
log->add( ). "you don't even need to pass anything in, bro.
```
Suprisingly, it's not covered by an existing test case (```can_log_symsg``` use ```anon_log->add( symsg ).````)

Do you agree? If so could you go back to a version compatible with the use case (and we could include this in #157)

**Comment by Kaszub09** [comment]
Why wouldn't it work?  `obj_to_log` should be equal to `syst_buffer` if it's not supplied, so those two lines are equivalent in that case 
``` 
      detailed_msg = add_syst_msg( syst_buffer ).  "executed earlier with no parameters
      detailed_msg = add_syst_msg( obj_to_log ).  "executed now with no parameters, but obj_to_log = syst_buffer 
```
You can verify it by changing `add` call in `can_log_symsg` test
```
   MESSAGE w001(BL) WITH 'This' 'is' 'a' 'test'.
    anon_log->add(  ).
```

**Comment by kjetil-kilhavn** [comment]
> Thanks for the PR. After reviewing, I think the following use case (which was advertised from [day one](https://community.sap.com/t5/application-development-blog-posts/show-scn-the-better-logger-i-promised/ba-p/13111590)) would not work anymore.
> 
> ```abap
> MESSAGE e001(oo) WITH foo bar baz INTO dummy.
> log->add( ). "you don't even need to pass anything in, bro.
> ```
> 
> Suprisingly, it's not covered by an existing test case (`can_log_symsg` use ```anon_log->add( symsg ).````)
> 
> Do you agree? If so could you go back to a version compatible with the use case (and we could include this in #157)

No, I disagree. ABAP Unit test methods: `can_add_to_log( )`, `can_add_to_named_log( )`, and `auto_saves_named_log( )`.

**Comment by mbtools** [comment]
Tests are covering the case. Lgtm 👍

**Review by AlexandreHT — APPROVED** [review]

**Comment by AlexandreHT** [comment]
Yes, you're right. Sorry about that. 
Thanks for the PR, It's merged.

**Pull request merged**
