### PR TITLE
Class to display entries from multiple instances (#81)

### PR DESCRIPTION
**Pull request by martinandrewcavanagh**
here is my suggested implementation. I'm using it successfully already.

### CODE REVIEW

**Comment by martinandrewcavanagh** [comment]
I don't quite get the last 3 abaplint findings. It looks 7.02 compliant to me...

**Comment by larshp** [comment]
EMPTY KEY is not possible in 702, use DEFAULT KEY instead

https://syntax.abaplint.org/?filter=data#/expression/TypeTable

**Comment by martinandrewcavanagh** [comment]
I switch between S/4 1909, ABAP 7.5, ABAP 7.4 often and sometimes I do miss the odd features in older versions. But gosh I'm happy that I don't have much to do with ABAP 7.02 anymore...

**Comment by larshp** [comment]
its basically impossible to remember the syntax for each version, but we have computers to remind us :)

**Comment by AlexandreHT** [comment]
I'm still not at ease with the signature of ```display_logs```. You have to look into the method to know that ```display_profile_head_size``` and ``` display_profile_tree``` size won't be taken into account if you provide a ```display_profile ```. I would very much prefer to make it 2 different methods. 
Would it be an acceptable solution? (Disagreeing opinions are welcome).

**Comment by martinandrewcavanagh** [comment]
I do love constructive cristim (although its a bit easier if you're in a developer project room rather than a forum)! 

I did consider making a create_display_profile a public method - but its not clear to me that this would belong in the collection class (or in any other currently existing class)... 

What we certainly could consider, is moving display_profile_head_size and display_profile_tree to the settings class/interface - I can't remember having changed those values in any previous programm of mine with a BAL log. I have however at times needed a different display profile - so it is important to be able to supply this via the optional parameter.

**Comment by pokrakam** [comment]
I agree that individual methods are a clearer way to implement mutually exclusive parameters.
Suggest making the most common use case the simplest and additional methods for specialised cases. Something like `display_logs` with optional size/tree parameters (or sensible defaults), and an additional `display_logs_using_profile` method.

**Comment by martinandrewcavanagh** [comment]
Yes, 2 different public methods does seem like a simple way of solving this, I've adjusted my draft solution accordingly,
This avoids creating new values in the settings and even allows me to remove a l_ prefix, for an otherwise identically names variable.

**Comment by martinandrewcavanagh** [comment]
@AlexandreHT @larshp  is there anything holding this back from being merged?

**Comment by larshp** [comment]
I'm not a maintainer of this project, so I cannot merge it, no time and no access :)

**Review by AlexandreHT — APPROVED** [review]

**Comment by AlexandreHT** [comment]
I felt into the "I'll have a deeper look later" trap. all good to me, it's merged. 
Thanks!

**Pull request merged**
