### PR TITLE
refactor: Clean ABAP changes

### PR DESCRIPTION
**Pull request by jelliottp**
Various clean code fixes and cleanup, including new abapLint rules enabled.

@AlexandreHT do you plan to keep this compatible with 7.02 for the time being? There could be quite a bit more cleaned up if it were upgraded.

### CODE REVIEW

**Comment by mbtools** [comment]
I'm using it for 702 and up. Let's keep it that way :-)  (Alternative, would be to setup an automatic [downport](https://rules.abaplint.org/downport/) with abaplint). 

PS: The clean-up is certainly appreciated. It's a lot... keep it even smaller in scope. One change at a time: `cl_aunit_assert` to `cl_abap_unit_assert`, fixing the `space dot`, updating comments, ... This will increase speed of review and the likelihood of getting changes merged 😃

**Comment by jelliottp** [comment]
Totally understand. I expected this to be small once I started, but kept finding more little things to correct.

**Comment by mbtools** [comment]
I gave it a quick test and it works fine. LGTM 👍

**Comment by AlexandreHT** [comment]
> @AlexandreHT do you plan to keep this compatible with 7.02 for the time being? There could be quite a bit more cleaned up if it were upgraded.

I'm open to discussion but fondamentally yes. abapGit and abap2xlsx are also compatible with 7.02, it seemed relevant to me to be aligned with these two huge projects.

**Comment by mbtools** [comment]
it's blocking other changes. can we merge?

**Comment by AlexandreHT** [comment]
We could but it's flagged as draft. Is is on purpose or is it a mistake?

**Comment by mbtools** [comment]
@jelliottp it looks good to me. Anything else you want to add?

**Comment by jelliottp** [comment]
Ready to go

**Review by AlexandreHT — APPROVED** [review]

**Comment by AlexandreHT** [comment]
Thanks

**Pull request merged**
