### PR TITLE
Application logs : various log formats , display context #108 and Demo programs 

### PR DESCRIPTION
**Pull request by vidyadharg**
Application logs various log formats. #108  #71 

This change displays different log formats as explained in the SAP demo program SBAL_DEMO_04. also it allows to set default context and display context fields in the log.

- Changes in zif_logger

<s>
1. METHOD zif_logger->set_default_context and zif_logger->get_default_context.
   new methods : used to set default context so that no need to pass context with every logged message.</s>

2. METHOD zif_logger->fullscreen.
   changes : display log as per display profile and context
3. METHOD zif_logger->add.
  change : update context table name
<s>4. METHOD zif_logger->export_to_table_with_context
  change : export table with context</s>
   
- Changes in settings class

1. zif_logger_settings->set_context_tabname and zif_logger_settings->get_context_tabname.
  new method : to capture context table name 

2. zif_logger_settings->set_display_profile and zif_logger_settings->get_display_profile.
 new method : to capture display profile and profile name.
 
3. get_standard_display_profile
  new method : to get standard display profile using FM used 'BAL_DSP_PROFILE_STANDARD_GET'

4. get_no_tree_display_profile
  new method : to get Fullscreen / no_tree display profile using FM used 'BAL_DSP_PROFILE_NO_TREE_GET'

5. get_single_display_profile
  new method : to get single display profile using FM used 'BAL_DSP_PROFILE_SINGLE_LOG_GET'

6. get_self_display_profile
  new method : to get user defined display profile

7. get_fcat_fm_context_tab
  new method : to fill message field catlog with context fields using context table name.

Demo program test screen shots 
demo program Selection.
image
 
o	Single Display log (Program ZDEMO_LOGGER04_SINGLE) 
image

o	Standard Display log (program ZDEMO_LOGGER04_STANDARD) 
image

o	Display without a tree (Program ZDEMO_LOGGER04_NO_TREE) - Fullscreen
image

o	Display select defined (Program ZDEMO_LOGGER04_self) 
image

<s>o	Display export table with context tab(Program zdemo_logger_export_contextab) </s>

### CODE REVIEW

**Comment by andkopp** [comment]
Hi @vidyadharg. Thanks a lot for your contribution. I have to admit that I have not looked into your pull request yet but I am going to. I am not yet familiar with the functions you have added to the logger. Give me some time and I will give you feedback.

**Comment by AlexandreHT** [comment]
Hi, sorry for the delay. When I did a quick review I noted the following points:

- ABAP2XLSX recently decided to move its demo programs in a dedicated repo (cf. https://github.com/abap2xlsx/abap2xlsx/issues/861)
- I'm not comfortable with methods zif_logger->set_default_context. Imho, context is associated to a log record. It seems awkward, to define a default context for all forthcoming logs. (I'm afraid it opens the door to a pattern where a developper has to check before every log->add( ) whether or not a default context has been defined).
Unless anyone has a productive use case, I suggest we don't implement it (even though the function is provided by standard SAP).

**Comment by vidyadharg** [comment]
Hi,

I will create another repository for the demo program.

Its not mandatory to set_default_context or pass context via log->add().
if context set via set_default_context or log->add() then only context fields will be part of log output otherwise it will be same as its now.

I find, that methods zif_logger->set_default_context give the flexibility to set the context once for following messages until the next context. otherwise, we must pass the context with all the log->add().

code example...
```
 log->s( 'Process started'). "here there is no context so it will be blank

"set context once at every new customer 
LOOP at Customers into customer.
  AT NEW customer.
    log->set_default_context( customer ).
  ENDAT.
 ....other processing logic.
  log->add( ).
  log->e( ).
ENDLOOP.

"Otherwise we have to pass context to every message.
LOOP at customers into customer.
....other processing logic.
  log->add( context = customer ).
  log->e( context = customer ).
ENDLOOP.

 log->s( 'Process Complete'). "here there is no context so it will be blank
```

**Comment by vidyadharg** [comment]
I have removed demos from the pull request. I can add them in other repo like "ABAP-Logger/demos".

**Comment by vidyadharg** [comment]
> Hi,
> 
> I will create another repository for the demo program.
> 
> Its not mandatory to set_default_context or pass context via log->add(). if context set via set_default_context or log->add() then only context fields will be part of log output otherwise it will be same as its now.
> 
> I find, that methods zif_logger->set_default_context give the flexibility to set the context once for following messages until the next context. otherwise, we must pass the context with all the log->add().
> 
> code example...
> 
> ```
>  log->s( 'Process started'). "here there is no context so it will be blank
> 
> "set context once at every new customer 
> LOOP at Customers into customer.
>   AT NEW customer.
>     log->set_default_context( customer ).
>   ENDAT.
>  ....other processing logic.
>   log->add( ).
>   log->e( ).
> ENDLOOP.
> 
> "Otherwise we have to pass context to every message.
> LOOP at customers into customer.
> ....other processing logic.
>   log->add( context = customer ).
>   log->e( context = customer ).
> ENDLOOP.
> 
>  log->s( 'Process Complete'). "here there is no context so it will be blank
> ```

any comment on this.?

**Comment by mbtools** [comment]
@vidyadharg I agree with @AlexandreHT regarding the context. 

In your example, you set the context once for each customer. The context is then automatically applied to all further messages. This just adds repetitive data to the log making it harder to read. If the subsequent message have additional details for the context (filling other fields), then you will have to supply the complete context anyway.

I think the nicer solution for your example is using a tree with a log level at "customer" where your add the context once and then a level below for the detailed messages (without repeating the context). If you show it like in ZDEMO_LOGGER04_self, this works very well. 

I do like your demo programs. Very helpful. Yes, please add them to https://github.com/ABAP-Logger/demos 😀 

On a general note, smaller PRs are better for reviewing (and getting approved 😉 ). Maybe split "display profile" and "context" changes into separate PRs.

**Comment by AlexandreHT** [comment]
Hi, I was about to import your code in my system to see it run, but I'm stuck an issue with abapGit : https://github.com/abapGit/abapGit/issues/5652

do you?

**Comment by vidyadharg** [comment]
> Hi, I was about to import your code in my system to see it run, but I'm stuck an issue with abapGit : [abapGit/abapGit#5652](https://github.com/abapGit/abapGit/issues/5652)
> 
> do you?

Hi,

I did a few local changes and reimported the repo and didn't get any errors.

I have ZABAPGIT_STANDALONE  1.115.0 (Standalone Version) * abapmerge 0.14.3 - 2022-06-21T11:06:29.534Z

**Comment by AlexandreHT** [comment]
Hi @vidyadharg, finally I have (finally) been able to play around your solution and there are some points I'd like to discuss further.

# On context
It's definitely what took me so long, but now I'm ok with your solution. (for the record, I wanted to find how BAL functions were handling the case of a log with 2 contexts defined on 2 different DDIC structures. It turns out it logs everything but only displays one of the 2 contexts depending of the tablename provided.)

# On profile
  * Could you rename set/get_display_profile into set/get_default_display_profile (because it can be overrrun by another profile in parameters)
  * In set_display_profile, it would be convenient to be able give context table_name alternatively to a context variable. Maybe i_context could be rename i_context_variable
  * I think the solution of a separate display profile class (#119) is more suitable than add the methods get_standard_display_profile, get_no_tree_display_profile, get_single_display_profile, get_self_display_profile. Could you remove these methods

Thanks and sorry once again for the delay.

**Comment by vidyadharg** [comment]
Hi @AlexandreHT,

I agree that a separate class for display profiles is a better approach. Please review and pull [class for display profile #119)](https://github.com/ABAP-Logger/ABAP-Logger/pull/119). 

once PR 119 is merged, I can adjust the [demo programs](https://github.com/ABAP-Logger/demos).

Vidyadhar.

**Comment by AlexandreHT** [comment]
@vidyadharg : #119 is merged, you can go on.

**Comment by AlexandreHT** [comment]
Hi @vidyadharg, 
I saw you closed the PR (which was almost finish if I remember well). Is it a mistake or do you not wish to continue this topic further? 
Thanks & Regards, 
Alexandre

**Comment by vidyadharg** [comment]
display profile changes are done by [Ennowulff](https://github.com/Ennowulff) in  [PR 119](https://github.com/ABAP-Logger/ABAP-Logger/pull/119). also, PR119 merged so my changes are not required any more.

**Pull request closed without merging**
