### PR TITLE
Enhancement: Logging Runtime Measurement

### PR DESCRIPTION
**Pull request by mbtools**
This adds an easy to use timer for basic runtime measurements:

```abap
log->timer_start( ).

* your code

log->timer_end( ).
```

This measures the runtime of your code and adds it as an info message to the log:

```
Runtime: x.xx seconds
```

Optionally, you can set a title for the start and end of the timer:

```abap
log->timer_start( 'Start measurement' ).
* your code
log->timer_end( 'End measurement' ).
```

```
Start measurement
... your log...
End measurement: x.xx seconds
```

### CODE REVIEW

**Comment by AlexandreHT** [comment]
Hi, it's a nice feature but I'm not sure ABAP logger should handle a timer (it looks like against Single-responsability principle). @andkopp, what do you think?

**Comment by mbtools** [comment]
well, the log messages are already timestamped (you can add the column in slg1). so the timer is a more convenient and precise feature 😃 

image

**Comment by andkopp** [comment]
> Hi, it's a nice feature but I'm not sure ABAP logger should handle a timer (it looks like against Single-responsability principle). @andkopp, what do you think?

I totally agree. I think, it is useful, but it just does not seem to fit as a logger method.
I didn‘t know that it is possible to add a column in SLG1 (and hopefully also in SLGD?).

**Comment by mbtools** [comment]
No problem. Easy enough to put the timer into a separate clas a f pass the timer output to the logger. 🙂

**Pull request closed without merging**
