### PR TITLE
Introduce callback parameters

### PR DESCRIPTION
**Pull request by christianguenter2**
#117

### CODE REVIEW

**Review by Ennowulff — APPROVED** [review]
looks good to me
thanks!

**Review by Ennowulff — APPROVED** [review]
looks good to me. thanks!

**Review by Ennowulff — APPROVED** [review]
looks good to me.
thanks! <3

**Comment by AlexandreHT** [comment]
Hi and thanks for the PR. 
May I suggest `callback_parameters` (or something similar) as a more descriptive variable name? (Unless it can be used for other stuff than callback).
BR Alexandre

**Comment by christianguenter2** [comment]
@AlexandreHT good idea. I changed it accordingly.

**Review by AlexandreHT — APPROVED** [review]

**Pull request merged**
